language: python

sudo: required

python:
  - 2.7
  - 3.5
  - 3.6

env:
  - NCO_VERSION=apt
  - NCO_VERSION=4.5.5
  - NCO_VERSION=4.6.1
  - NCO_VERSION=4.6.6

addons:
  apt:
    packages:
      - nco

before_install:
  # Install miniconda
  # -----------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda
  - wget ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add create_default_packages pip
  - conda update --quiet conda

  # Add 3rd party channels
  # ------------------------------------
  - conda config --add channels conda-forge

  # Create our environment
  # ------------------------------------
  - conda env create --quiet --file ci/requirements-$TRAVIS_PYTHON_VERSION.yml
  - source activate test_env
  - if [ "${NCO_VERSION}" == "apt" ];
    then sudo apt-get -qq update && sudo apt-get install -y netcdf-bin libnetcdf-dev nco;
    else conda install nco==${NCO_VERSION};
    fi

  # Debugging information
  # ------------------------------------
  - conda info -a
  - conda list --export
  - which ncks ncdump

  # Install pynco
  # ------------------------------------
  - python setup.py install

# command to run tests
script:
  - python -c "from nco import Nco"
  - py.test
